# Generated by Django 3.2.7 on 2021-10-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_submissions_pgid"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissions",
            name="sub_time",
            field=models.TimeField(auto_now=True),
        ),
    ]
